### ISSUE TITLE
Different version node with pigsty-moloch-plugin and pigsty

### ISSUE THREAD

**Issue by brodecm** [hillar/pigsty-moloch-plugin#6]
Hi guys, I'm sorry for my English. I installed pigsty with node version 0.10.48. I tried to run pigsty and it's successfull, but when i installed pigsty moloch plugin, i  must changed node version on 4.8.2, because i got error with hashtable(with version 0.10.48).   

$ pigsty
[-] Pigsty is starting up...
[!] There was a problem installing the output plugin: pigsty-moloch-plugin
[!] Error was: { [Error: Cannot find module 'pigsty-moloch-plugin'] code: 'MODULE_NOT_FOUND' }
[!] Do you have the plugin installed? Try doing: npm install pigsty-moloch-plugin -g
[!] Have a special day. ♥

$ git clone https://github.com/hillar/pigsty-moloch-plugin.git
$ cd pigsty-moloch-plugin/

$ n 4
root@projekt:/usr/local/lib/node_modules/pigsty/pigsty-moloch-plugin# node -v
v4.8.2

$ npm install
$ npm WARN package.json pigsty-moloch-plugin@0.0.1 No license field.
-
> hashtable@2.0.2 install /usr/local/lib/node_modules/pigsty/pigsty-moloch-plugin/node_modules/hashtable
> node-gyp configure build

make: Entering directory '/usr/local/lib/node_modules/pigsty/pigsty-moloch-plugin/node_modules/hashtable/build'
  CXX(target) Release/obj.target/native/src/hashtable.o
  SOLINK_MODULE(target) Release/obj.target/native.node
  COPY Release/native.node
make: Leaving directory '/usr/local/lib/node_modules/pigsty/pigsty-moloch-plugin/node_modules/hashtable/build'
hashtable@2.0.2 node_modules/hashtable
└── nan@2.5.1

And when node version is changed to 4.8.2 and i run pigsty, this is output :

$ pigsty
/usr/local/lib/node_modules/pigsty/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/usr/local/lib/node_modules/pigsty/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/pigsty/node_modules/ref/lib/ref.js:5:47)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

When i changed version to 0.10.48, my output is follow:  
$ pigsty
[-] Pigsty is starting up...
[!] There was a problem installing the output plugin: pigsty-moloch-plugin
[!] Error was: { [Error: Cannot find module 'pigsty-moloch-plugin'] code: 'MODULE_NOT_FOUND' }
[!] Do you have the plugin installed? Try doing: npm install pigsty-moloch-plugin -g
[!] Have a special day. ♥

**Comment by hillar** [comment]
sorry, this module is out of date, because unified2 have been replaced with json
see 
* https://github.com/ccdcoe/CDMCS/tree/master/Moloch/vagrant/singlehost#moloch--suricata--eek-in-single-box
* https://gist.github.com/hillar/d721f0e98bc748b90108cb162fbc14c7
* https://gist.github.com/hillar/409a18e1604c70bb3804

**Comment by brodecm** [comment]
This solution is effective even for Snort or only  for Suricata ?

**Comment by brodecm** [comment]
Hi. Can this solution be used with Snort or only for Suricata. U2 format saved with Snort is possible convert to json, but it’s possible for your scripts to run with Suricata ?
